### ISSUE TITLE
Uppercase field parameter to compute yields a 400 Bad parameter

### ISSUE THREAD

**Issue by claussI** [castorjs/castor-core#11]
A `http://localhost:3000/compute.json?o=distinct&f=PRF` yieds a `400 Bad parameter`, though `http://localhost:3000/compute.json?o=distinct&f=Prf` works well.

https://github.com/castorjs/castor-core/blob/master/routes/compute.js#L78 shows that the pattern for `field` parameter is `"pattern" : "[a-z*-][a-z0-9*. _-]*"`, so the field names should be lowercase, but `Prf` does not respect this.

**Comment by parmentf** [comment]
In my opinion, the trouble comes from the pattern: if the pattern is found in the field name, then it is valid.

`Prf` is valid, because there is 2 lowercase letters in it (`[a-z*-]`).

`PRF` is not, because none of its characters match `[a-z*-]`.

I think the first intention was to add `^` and ` $` to the pattern, to ensure that the pattern covers the whole name: `^[a-z*-][a-z0-9*. _-]*$`.

But, if we use that new pattern, we will break the ascendant compatibility (`Prf`, for example won't be valid any more, because its first character is an uppercase letter).

I suggest that we use `^[a-z*A-Z-][a-zA-Z0-9*. _-]*$` instead, in order to allow uppercase letters.

Also, I don't understand the presence of the `*` character inside the brackets, it does not have any utility. So `^[a-zA-Z-][a-zA-Z0-9. _-]*$` would be better.

> *Note:* the dot character in the brackets acts the dot character (not any character), [because it is within brackets](http://stackoverflow.com/questions/10397968/escape-dot-in-a-regex-range).
